const fs = require('fs');

const svgContent = fs.readFileSync('src/components/YantraSVG.tsx', 'utf8');

// We want to replace the paths generated by gates.forEach.
// Let's just rewrite the whole file cleanly.

const svg = [];
svg.push('import React from "react";\n\nexport default function YantraSVG({ className }: { className?: string }) {\n  return (\n    <svg viewBox="0 0 1000 1000" className={className} fill="none" stroke="currentColor" strokeWidth="2.5">');

// 1. Bhupura (Outer Square with Gates)
const gates = [
  { size: 920, gateW: 160, gateD: 50 },
  { size: 870, gateW: 130, gateD: 50 },
  { size: 820, gateW: 100, gateD: 50 },
];

gates.forEach((g) => {
  const s = g.size; // total width/height of the square
  const gw = g.gateW; // width of the T-gate opening
  const gd = g.gateD; // depth of the T-gate (sticking outwards)
  
  const m = (1000 - s) / 2; // margin (inner bound of the line)
  const mx = 1000 - m; // max bound of the line
  
  const c = 500;
  const hw = gw / 2;
  
  // A gate goes OUTWARDS. 
  // Let's trace from top-left corner clockwise.
  // Top-left: (m, m)
  // Go right to gate: L (c - hw, m)
  // Go out: L (c - hw, m - gd)
  // Go right: L (c + hw, m - gd)
  // Go in: L (c + hw, m)
  // Go right to top-right corner: L (mx, m)
  // Go down to right gate: L (mx, c - hw)
  // Go out: L (mx + gd, c - hw)
  // Go down: L (mx + gd, c + hw)
  // Go in: L (mx, c + hw)
  // Go down to bottom-right corner: L (mx, mx)
  // Go left to bottom gate: L (c + hw, mx)
  // Go out: L (c + hw, mx + gd)
  // Go left: L (c - hw, mx + gd)
  // Go in: L (c - hw, mx)
  // Go left to bottom-left corner: L (m, mx)
  // Go up to left gate: L (m, c + hw)
  // Go out: L (m - gd, c + hw)
  // Go up: L (m - gd, c - hw)
  // Go in: L (m, c - hw)
  // Close to top-left: Z
  
  const path = `M ${m},${m} L ${c - hw},${m} L ${c - hw},${m - gd} L ${c + hw},${m - gd} L ${c + hw},${m} L ${mx},${m} L ${mx},${c - hw} L ${mx + gd},${c - hw} L ${mx + gd},${c + hw} L ${mx},${c + hw} L ${mx},${mx} L ${c + hw},${mx} L ${c + hw},${mx + gd} L ${c - hw},${mx + gd} L ${c - hw},${mx} L ${m},${mx} L ${m},${c + hw} L ${m - gd},${c + hw} L ${m - gd},${c - hw} L ${m},${c - hw} Z`;
    
  svg.push(`      <path d="${path}" />`);
});

// 2. The 3 outermost concentric circles
svg.push('      <circle cx="500" cy="500" r="390" />');
svg.push('      <circle cx="500" cy="500" r="375" />');
svg.push('      <circle cx="500" cy="500" r="360" />');

// 3. 16 Petals (from r=290 to r=360)
svg.push('      <g strokeWidth="2.5">');
for(let i=0; i<16; i++) {
  const angle = i * 22.5;
  svg.push(`        <path d="M 500,140 Q 525,175 500,210 Q 475,175 500,140 Z" transform="rotate(${angle} 500 500)" />`);
}
svg.push('      </g>');
svg.push('      <circle cx="500" cy="500" r="290" />');

// 4. 8 Petals (from r=220 to r=290)
svg.push('      <g strokeWidth="2.5">');
for(let i=0; i<8; i++) {
  const angle = i * 45;
  svg.push(`        <path d="M 500,210 Q 545,245 500,280 Q 455,245 500,210 Z" transform="rotate(${angle} 500 500)" />`);
}
svg.push('      </g>');
svg.push('      <circle cx="500" cy="500" r="220" />');

// 5. 9 Triangles (Sri Yantra)
svg.push('      <g strokeWidth="2.5">');

const cx = 500;
const cy = 500;
const r = 220;

function getX(y) {
  const dy = y - cy;
  const dx2 = r*r - dy*dy;
  if (dx2 < 0) return cx;
  return Math.sqrt(dx2);
}

const shakti_bases_prop = [0.31, 0.16, -0.05, -0.19, -0.32];
const shakti_points_prop = [-1.0, -0.85, -0.66, -0.50, -0.28];
const shiva_bases_prop = [-0.31, 0.0, 0.22, 0.35];
const shiva_points_prop = [1.0, 0.85, 0.66, 0.52];

for(let i=0; i<5; i++) {
  const baseY = 500 - (shakti_bases_prop[i] * r);
  const pointY = 500 - (shakti_points_prop[i] * r);
  let dx = getX(baseY) - cx;
  if (i > 0) dx *= (1 - i*0.1); 
  svg.push(`        <polygon points="${cx},${pointY} ${cx + dx},${baseY} ${cx - dx},${baseY}" />`);
}

for(let i=0; i<4; i++) {
  const baseY = 500 - (shiva_bases_prop[i] * r);
  const pointY = 500 - (shiva_points_prop[i] * r);
  let dx = getX(baseY) - cx;
  if (i > 0) dx *= (1 - i*0.12);
  svg.push(`        <polygon points="${cx},${pointY} ${cx + dx},${baseY} ${cx - dx},${baseY}" />`);
}

svg.push('      </g>');
svg.push('      <circle cx="500" cy="500" r="4" fill="currentColor" />');
svg.push('    </svg>\n  );\n}\n');

fs.writeFileSync('src/components/YantraSVG.tsx', svg.join('\n'));
